# ruff: noqa: RUF100, E501, PYI002, PYI029, PYI046, PYI047, N801, N802, N803, N805, I001
from concurrent.futures import Future
from ctypes import c_void_p
from enum import Enum, IntEnum, IntFlag
from fractions import Fraction
from inspect import Signature
from logging import Handler, LogRecord, StreamHandler
from types import MappingProxyType, TracebackType
from typing import Any, Callable, Concatenate, Final, IO, Iterable, Iterator, Literal, Mapping, MutableMapping, NamedTuple, Protocol, Self, SupportsInt, TextIO, TypedDict, final, overload
from warnings import deprecated
from weakref import ReferenceType


__all__ = [
    "CHROMA_BOTTOM",
    "CHROMA_BOTTOM_LEFT",
    "CHROMA_CENTER",
    "CHROMA_LEFT",
    "CHROMA_TOP",
    "CHROMA_TOP_LEFT",
    "FIELD_BOTTOM",
    "FIELD_PROGRESSIVE",
    "FIELD_TOP",
    "FLOAT",
    "GRAY",
    "GRAY8",
    "GRAY9",
    "GRAY10",
    "GRAY12",
    "GRAY14",
    "GRAY16",
    "GRAY32",
    "GRAYH",
    "GRAYS",
    "INTEGER",
    "NONE",
    "RANGE_FULL",
    "RANGE_LIMITED",
    "RGB",
    "RGB24",
    "RGB27",
    "RGB30",
    "RGB36",
    "RGB42",
    "RGB48",
    "RGBH",
    "RGBS",
    "YUV",
    "YUV410P8",
    "YUV411P8",
    "YUV420P8",
    "YUV420P9",
    "YUV420P10",
    "YUV420P12",
    "YUV420P14",
    "YUV420P16",
    "YUV420PH",
    "YUV420PS",
    "YUV422P8",
    "YUV422P9",
    "YUV422P10",
    "YUV422P12",
    "YUV422P14",
    "YUV422P16",
    "YUV422PH",
    "YUV422PS",
    "YUV440P8",
    "YUV444P8",
    "YUV444P9",
    "YUV444P10",
    "YUV444P12",
    "YUV444P14",
    "YUV444P16",
    "YUV444PH",
    "YUV444PS",
    "clear_output",
    "clear_outputs",
    "core",
    "get_output",
    "get_outputs",
]

type _AnyStr = str | bytes | bytearray

type _VSValueSingle = (
    int | float | _AnyStr | RawFrame | VideoFrame | AudioFrame | RawNode | VideoNode | AudioNode | Callable[..., Any]
)

type _VSValueIterable = (
    _SupportsIter[int]
    | _SupportsIter[_AnyStr]
    | _SupportsIter[float]
    | _SupportsIter[RawFrame]
    | _SupportsIter[VideoFrame]
    | _SupportsIter[AudioFrame]
    | _SupportsIter[RawNode]
    | _SupportsIter[VideoNode]
    | _SupportsIter[AudioNode]
    | _SupportsIter[Callable[..., Any]]
    | _GetItemIterable[int]
    | _GetItemIterable[float]
    | _GetItemIterable[_AnyStr]
    | _GetItemIterable[RawFrame]
    | _GetItemIterable[VideoFrame]
    | _GetItemIterable[AudioFrame]
    | _GetItemIterable[RawNode]
    | _GetItemIterable[VideoNode]
    | _GetItemIterable[AudioNode]
    | _GetItemIterable[Callable[..., Any]]
)
type _VSValue = _VSValueSingle | _VSValueIterable

class _SupportsIter[_T](Protocol):
    def __iter__(self) -> Iterator[_T]: ...

class _SequenceLike[_T](Protocol):
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...

class _GetItemIterable[_T](Protocol):
    def __getitem__(self, i: int, /) -> _T: ...

class _SupportsKeysAndGetItem[_KT, _VT](Protocol):
    def __getitem__(self, key: _KT, /) -> _VT: ...
    def keys(self) -> Iterable[_KT]: ...

class _VSCallback(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> _VSValue: ...

# Known callback signatures
# _VSCallback_{plugin_namespace}_{Function_name}_{parameter_name}
class _VSCallback_akarin_PropExpr_dict(Protocol):
    def __call__(
        self,
    ) -> Mapping[
        str,
        int
        | float
        | _AnyStr
        | _SupportsIter[int]
        | _SupportsIter[_AnyStr]
        | _SupportsIter[float]
        | _GetItemIterable[int]
        | _GetItemIterable[float]
        | _GetItemIterable[_AnyStr],
    ]: ...

class _VSCallback_descale_Decustom_custom_kernel(Protocol):
    def __call__(self, *, x: float) -> float: ...

class _VSCallback_descale_ScaleCustom_custom_kernel(Protocol):
    def __call__(self, *, x: float) -> float: ...

class _VSCallback_std_FrameEval_eval_0(Protocol):
    def __call__(self, *, n: int) -> VideoNode: ...

class _VSCallback_std_FrameEval_eval_1(Protocol):
    def __call__(self, *, n: int, f: VideoFrame) -> VideoNode: ...

class _VSCallback_std_FrameEval_eval_2(Protocol):
    def __call__(self, *, n: int, f: list[VideoFrame]) -> VideoNode: ...

class _VSCallback_std_FrameEval_eval_3(Protocol):
    def __call__(self, *, n: int, f: VideoFrame | list[VideoFrame]) -> VideoNode: ...

type _VSCallback_std_FrameEval_eval = (  # noqa: PYI047
    _VSCallback_std_FrameEval_eval_0
    | _VSCallback_std_FrameEval_eval_1
    | _VSCallback_std_FrameEval_eval_2
    | _VSCallback_std_FrameEval_eval_3
)

class _VSCallback_std_Lut_function_0(Protocol):
    def __call__(self, *, x: int) -> int: ...

class _VSCallback_std_Lut_function_1(Protocol):
    def __call__(self, *, x: float) -> float: ...

type _VSCallback_std_Lut_function = _VSCallback_std_Lut_function_0 | _VSCallback_std_Lut_function_1  # noqa: PYI047

class _VSCallback_std_Lut2_function_0(Protocol):
    def __call__(self, *, x: int, y: int) -> int: ...

class _VSCallback_std_Lut2_function_1(Protocol):
    def __call__(self, *, x: float, y: float) -> float: ...

type _VSCallback_std_Lut2_function = _VSCallback_std_Lut2_function_0 | _VSCallback_std_Lut2_function_1  # noqa: PYI047

class _VSCallback_std_ModifyFrame_selector_0(Protocol):
    def __call__(self, *, n: int, f: VideoFrame) -> VideoFrame: ...

class _VSCallback_std_ModifyFrame_selector_1(Protocol):
    def __call__(self, *, n: int, f: list[VideoFrame]) -> VideoFrame: ...

class _VSCallback_std_ModifyFrame_selector_2(Protocol):
    def __call__(self, *, n: int, f: VideoFrame | list[VideoFrame]) -> VideoFrame: ...

type _VSCallback_std_ModifyFrame_selector = (  # noqa: PYI047
    _VSCallback_std_ModifyFrame_selector_0
    | _VSCallback_std_ModifyFrame_selector_1
    | _VSCallback_std_ModifyFrame_selector_2
)

class _VSCallback_resize2_Custom_custom_kernel(Protocol):
    def __call__(self, *, x: float) -> float: ...

class LogHandle: ...

class PythonVSScriptLoggingBridge(Handler):
    def __init__(self, parent: StreamHandler[TextIO], level: int | str = ...) -> None: ...
    def emit(self, record: LogRecord) -> None: ...

class Error(Exception):
    value: Any
    def __init__(self, value: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

# Environment SubSystem
@final
class EnvironmentData: ...

class EnvironmentPolicy:
    def on_policy_registered(self, special_api: EnvironmentPolicyAPI) -> None: ...
    def on_policy_cleared(self) -> None: ...
    def get_current_environment(self) -> EnvironmentData | None: ...
    def set_environment(self, environment: EnvironmentData | None) -> EnvironmentData | None: ...
    def is_alive(self, environment: EnvironmentData) -> bool: ...

@final
class StandaloneEnvironmentPolicy:
    def on_policy_registered(self, api: EnvironmentPolicyAPI) -> None: ...
    def on_policy_cleared(self) -> None: ...
    def get_current_environment(self) -> EnvironmentData: ...
    def set_environment(self, environment: EnvironmentData | None) -> EnvironmentData: ...
    def is_alive(self, environment: EnvironmentData) -> bool: ...
    def _on_log_message(self, level: MessageType, msg: str) -> None: ...

@final
class VSScriptEnvironmentPolicy:
    def on_policy_registered(self, policy_api: EnvironmentPolicyAPI) -> None: ...
    def on_policy_cleared(self) -> None: ...
    def get_current_environment(self) -> EnvironmentData | None: ...
    def set_environment(self, environment: EnvironmentData | None) -> EnvironmentData | None: ...
    def is_alive(self, environment: EnvironmentData) -> bool: ...

@final
class EnvironmentPolicyAPI:
    def wrap_environment(self, environment_data: EnvironmentData) -> Environment: ...
    def create_environment(self, flags: SupportsInt = 0) -> EnvironmentData: ...
    def set_logger(self, env: EnvironmentData, logger: Callable[[int, str], None]) -> None: ...
    def get_vapoursynth_api(self, version: int) -> c_void_p: ...
    def get_core_ptr(self, environment_data: EnvironmentData) -> c_void_p: ...
    def destroy_environment(self, env: EnvironmentData) -> None: ...
    def unregister_policy(self) -> None: ...

def register_policy(policy: EnvironmentPolicy) -> None: ...
def has_policy() -> bool: ...
def register_on_destroy(callback: Callable[..., None]) -> None: ...
def unregister_on_destroy(callback: Callable[..., None]) -> None: ...
def _try_enable_introspection(version: int | None = None) -> bool: ...
@final
class _FastManager:
    def __enter__(self) -> None: ...
    def __exit__(self, *_: object) -> None: ...

class Environment:
    env: Final[ReferenceType[EnvironmentData]]
    def __repr__(self) -> str: ...
    @overload
    def __eq__(self, other: Environment) -> bool: ...
    @overload
    def __eq__(self, other: object) -> bool: ...
    @property
    def alive(self) -> bool: ...
    @property
    def single(self) -> bool: ...
    @classmethod
    def is_single(cls) -> bool: ...
    @property
    def env_id(self) -> int: ...
    @property
    def active(self) -> bool: ...
    def copy(self) -> Self: ...
    def use(self) -> _FastManager: ...

class Local:
    def __getattr__(self, key: str) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __delattr__(self, key: str) -> None: ...

def get_current_environment() -> Environment: ...

class CoreTimings:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, enabled: bool) -> bool: ...
    @property
    def freed_nodes(self) -> bool: ...
    @freed_nodes.setter
    def freed_nodes(self, value: Literal[0]) -> bool: ...

# VapourSynth & plugin versioning

class VapourSynthVersion(NamedTuple):
    release_major: int
    release_minor: int
    def __str__(self) -> str: ...

class VapourSynthAPIVersion(NamedTuple):
    api_major: int
    api_minor: int
    def __str__(self) -> str: ...

__version__: VapourSynthVersion
__api_version__: VapourSynthAPIVersion

# Vapoursynth constants from vapoursynth.pyx

class MediaType(IntEnum):
    VIDEO = ...
    AUDIO = ...

VIDEO: Literal[MediaType.VIDEO]
AUDIO: Literal[MediaType.AUDIO]

class ColorFamily(IntEnum):
    UNDEFINED = ...
    GRAY = ...
    RGB = ...
    YUV = ...

UNDEFINED: Literal[ColorFamily.UNDEFINED]
GRAY: Literal[ColorFamily.GRAY]
RGB: Literal[ColorFamily.RGB]
YUV: Literal[ColorFamily.YUV]

class SampleType(IntEnum):
    INTEGER = ...
    FLOAT = ...

INTEGER: Literal[SampleType.INTEGER]
FLOAT: Literal[SampleType.FLOAT]

class PresetVideoFormat(IntEnum):
    NONE = ...

    GRAY8 = ...
    GRAY9 = ...
    GRAY10 = ...
    GRAY12 = ...
    GRAY14 = ...
    GRAY16 = ...
    GRAY32 = ...

    GRAYH = ...
    GRAYS = ...

    YUV420P8 = ...
    YUV422P8 = ...
    YUV444P8 = ...
    YUV410P8 = ...
    YUV411P8 = ...
    YUV440P8 = ...

    YUV420P9 = ...
    YUV422P9 = ...
    YUV444P9 = ...

    YUV420P10 = ...
    YUV422P10 = ...
    YUV444P10 = ...

    YUV420P12 = ...
    YUV422P12 = ...
    YUV444P12 = ...

    YUV420P14 = ...
    YUV422P14 = ...
    YUV444P14 = ...

    YUV420P16 = ...
    YUV422P16 = ...
    YUV444P16 = ...

    YUV420PH = ...
    YUV420PS = ...

    YUV422PH = ...
    YUV422PS = ...

    YUV444PH = ...
    YUV444PS = ...

    RGB24 = ...
    RGB27 = ...
    RGB30 = ...
    RGB36 = ...
    RGB42 = ...
    RGB48 = ...

    RGBH = ...
    RGBS = ...

NONE: Literal[PresetVideoFormat.NONE]

GRAY8: Literal[PresetVideoFormat.GRAY8]
GRAY9: Literal[PresetVideoFormat.GRAY9]
GRAY10: Literal[PresetVideoFormat.GRAY10]
GRAY12: Literal[PresetVideoFormat.GRAY12]
GRAY14: Literal[PresetVideoFormat.GRAY14]
GRAY16: Literal[PresetVideoFormat.GRAY16]
GRAY32: Literal[PresetVideoFormat.GRAY32]

GRAYH: Literal[PresetVideoFormat.GRAYH]
GRAYS: Literal[PresetVideoFormat.GRAYS]

YUV420P8: Literal[PresetVideoFormat.YUV420P8]
YUV422P8: Literal[PresetVideoFormat.YUV422P8]
YUV444P8: Literal[PresetVideoFormat.YUV444P8]
YUV410P8: Literal[PresetVideoFormat.YUV410P8]
YUV411P8: Literal[PresetVideoFormat.YUV411P8]
YUV440P8: Literal[PresetVideoFormat.YUV440P8]

YUV420P9: Literal[PresetVideoFormat.YUV420P9]
YUV422P9: Literal[PresetVideoFormat.YUV422P9]
YUV444P9: Literal[PresetVideoFormat.YUV444P9]

YUV420P10: Literal[PresetVideoFormat.YUV420P10]
YUV422P10: Literal[PresetVideoFormat.YUV422P10]
YUV444P10: Literal[PresetVideoFormat.YUV444P10]

YUV420P12: Literal[PresetVideoFormat.YUV420P12]
YUV422P12: Literal[PresetVideoFormat.YUV422P12]
YUV444P12: Literal[PresetVideoFormat.YUV444P12]

YUV420P14: Literal[PresetVideoFormat.YUV420P14]
YUV422P14: Literal[PresetVideoFormat.YUV422P14]
YUV444P14: Literal[PresetVideoFormat.YUV444P14]

YUV420P16: Literal[PresetVideoFormat.YUV420P16]
YUV422P16: Literal[PresetVideoFormat.YUV422P16]
YUV444P16: Literal[PresetVideoFormat.YUV444P16]

YUV420PH: Literal[PresetVideoFormat.YUV420PH]
YUV420PS: Literal[PresetVideoFormat.YUV420PS]

YUV422PH: Literal[PresetVideoFormat.YUV422PH]
YUV422PS: Literal[PresetVideoFormat.YUV422PS]

YUV444PH: Literal[PresetVideoFormat.YUV444PH]
YUV444PS: Literal[PresetVideoFormat.YUV444PS]

RGB24: Literal[PresetVideoFormat.RGB24]
RGB27: Literal[PresetVideoFormat.RGB27]
RGB30: Literal[PresetVideoFormat.RGB30]
RGB36: Literal[PresetVideoFormat.RGB36]
RGB42: Literal[PresetVideoFormat.RGB42]
RGB48: Literal[PresetVideoFormat.RGB48]

RGBH: Literal[PresetVideoFormat.RGBH]
RGBS: Literal[PresetVideoFormat.RGBS]

class FilterMode(IntEnum):
    PARALLEL = ...
    PARALLEL_REQUESTS = ...
    UNORDERED = ...
    FRAME_STATE = ...

PARALLEL: Literal[FilterMode.PARALLEL]
PARALLEL_REQUESTS: Literal[FilterMode.PARALLEL_REQUESTS]
UNORDERED: Literal[FilterMode.UNORDERED]
FRAME_STATE: Literal[FilterMode.FRAME_STATE]

class AudioChannels(IntEnum):
    FRONT_LEFT = ...
    FRONT_RIGHT = ...
    FRONT_CENTER = ...
    LOW_FREQUENCY = ...
    BACK_LEFT = ...
    BACK_RIGHT = ...
    FRONT_LEFT_OF_CENTER = ...
    FRONT_RIGHT_OF_CENTER = ...
    BACK_CENTER = ...
    SIDE_LEFT = ...
    SIDE_RIGHT = ...
    TOP_CENTER = ...
    TOP_FRONT_LEFT = ...
    TOP_FRONT_CENTER = ...
    TOP_FRONT_RIGHT = ...
    TOP_BACK_LEFT = ...
    TOP_BACK_CENTER = ...
    TOP_BACK_RIGHT = ...
    STEREO_LEFT = ...
    STEREO_RIGHT = ...
    WIDE_LEFT = ...
    WIDE_RIGHT = ...
    SURROUND_DIRECT_LEFT = ...
    SURROUND_DIRECT_RIGHT = ...
    LOW_FREQUENCY2 = ...

FRONT_LEFT: Literal[AudioChannels.FRONT_LEFT]
FRONT_RIGHT: Literal[AudioChannels.FRONT_RIGHT]
FRONT_CENTER: Literal[AudioChannels.FRONT_CENTER]
LOW_FREQUENCY: Literal[AudioChannels.LOW_FREQUENCY]
BACK_LEFT: Literal[AudioChannels.BACK_LEFT]
BACK_RIGHT: Literal[AudioChannels.BACK_RIGHT]
FRONT_LEFT_OF_CENTER: Literal[AudioChannels.FRONT_LEFT_OF_CENTER]
FRONT_RIGHT_OF_CENTER: Literal[AudioChannels.FRONT_RIGHT_OF_CENTER]
BACK_CENTER: Literal[AudioChannels.BACK_CENTER]
SIDE_LEFT: Literal[AudioChannels.SIDE_LEFT]
SIDE_RIGHT: Literal[AudioChannels.SIDE_RIGHT]
TOP_CENTER: Literal[AudioChannels.TOP_CENTER]
TOP_FRONT_LEFT: Literal[AudioChannels.TOP_FRONT_LEFT]
TOP_FRONT_CENTER: Literal[AudioChannels.TOP_FRONT_CENTER]
TOP_FRONT_RIGHT: Literal[AudioChannels.TOP_FRONT_RIGHT]
TOP_BACK_LEFT: Literal[AudioChannels.TOP_BACK_LEFT]
TOP_BACK_CENTER: Literal[AudioChannels.TOP_BACK_CENTER]
TOP_BACK_RIGHT: Literal[AudioChannels.TOP_BACK_RIGHT]
STEREO_LEFT: Literal[AudioChannels.STEREO_LEFT]
STEREO_RIGHT: Literal[AudioChannels.STEREO_RIGHT]
WIDE_LEFT: Literal[AudioChannels.WIDE_LEFT]
WIDE_RIGHT: Literal[AudioChannels.WIDE_RIGHT]
SURROUND_DIRECT_LEFT: Literal[AudioChannels.SURROUND_DIRECT_LEFT]
SURROUND_DIRECT_RIGHT: Literal[AudioChannels.SURROUND_DIRECT_RIGHT]
LOW_FREQUENCY2: Literal[AudioChannels.LOW_FREQUENCY2]

class MessageType(IntFlag):
    MESSAGE_TYPE_DEBUG = ...
    MESSAGE_TYPE_INFORMATION = ...
    MESSAGE_TYPE_WARNING = ...
    MESSAGE_TYPE_CRITICAL = ...
    MESSAGE_TYPE_FATAL = ...

MESSAGE_TYPE_DEBUG: Literal[MessageType.MESSAGE_TYPE_DEBUG]
MESSAGE_TYPE_INFORMATION: Literal[MessageType.MESSAGE_TYPE_INFORMATION]
MESSAGE_TYPE_WARNING: Literal[MessageType.MESSAGE_TYPE_WARNING]
MESSAGE_TYPE_CRITICAL: Literal[MessageType.MESSAGE_TYPE_CRITICAL]
MESSAGE_TYPE_FATAL: Literal[MessageType.MESSAGE_TYPE_FATAL]

class CoreCreationFlags(IntFlag):
    ENABLE_GRAPH_INSPECTION = ...
    DISABLE_AUTO_LOADING = ...
    DISABLE_LIBRARY_UNLOADING = ...

ENABLE_GRAPH_INSPECTION: Literal[CoreCreationFlags.ENABLE_GRAPH_INSPECTION]
DISABLE_AUTO_LOADING: Literal[CoreCreationFlags.DISABLE_AUTO_LOADING]
DISABLE_LIBRARY_UNLOADING: Literal[CoreCreationFlags.DISABLE_LIBRARY_UNLOADING]

# Vapoursynth constants from vsconstants.pyd

class ColorRange(IntEnum):
    RANGE_FULL = ...
    RANGE_LIMITED = ...

RANGE_FULL: Literal[ColorRange.RANGE_FULL]
RANGE_LIMITED: Literal[ColorRange.RANGE_LIMITED]

class ChromaLocation(IntEnum):
    CHROMA_LEFT = ...
    CHROMA_CENTER = ...
    CHROMA_TOP_LEFT = ...
    CHROMA_TOP = ...
    CHROMA_BOTTOM_LEFT = ...
    CHROMA_BOTTOM = ...

CHROMA_LEFT: Literal[ChromaLocation.CHROMA_LEFT]
CHROMA_CENTER: Literal[ChromaLocation.CHROMA_CENTER]
CHROMA_TOP_LEFT: Literal[ChromaLocation.CHROMA_TOP_LEFT]
CHROMA_TOP: Literal[ChromaLocation.CHROMA_TOP]
CHROMA_BOTTOM_LEFT: Literal[ChromaLocation.CHROMA_BOTTOM_LEFT]
CHROMA_BOTTOM: Literal[ChromaLocation.CHROMA_BOTTOM]

class FieldBased(IntEnum):
    FIELD_PROGRESSIVE = ...
    FIELD_TOP = ...
    FIELD_BOTTOM = ...

FIELD_PROGRESSIVE: Literal[FieldBased.FIELD_PROGRESSIVE]
FIELD_TOP: Literal[FieldBased.FIELD_TOP]
FIELD_BOTTOM: Literal[FieldBased.FIELD_BOTTOM]

class MatrixCoefficients(IntEnum):
    MATRIX_RGB = ...
    MATRIX_BT709 = ...
    MATRIX_UNSPECIFIED = ...
    MATRIX_FCC = ...
    MATRIX_BT470_BG = ...
    MATRIX_ST170_M = ...
    MATRIX_ST240_M = ...
    MATRIX_YCGCO = ...
    MATRIX_BT2020_NCL = ...
    MATRIX_BT2020_CL = ...
    MATRIX_CHROMATICITY_DERIVED_NCL = ...
    MATRIX_CHROMATICITY_DERIVED_CL = ...
    MATRIX_ICTCP = ...

MATRIX_RGB: Literal[MatrixCoefficients.MATRIX_RGB]
MATRIX_BT709: Literal[MatrixCoefficients.MATRIX_BT709]
MATRIX_UNSPECIFIED: Literal[MatrixCoefficients.MATRIX_UNSPECIFIED]
MATRIX_FCC: Literal[MatrixCoefficients.MATRIX_FCC]
MATRIX_BT470_BG: Literal[MatrixCoefficients.MATRIX_BT470_BG]
MATRIX_ST170_M: Literal[MatrixCoefficients.MATRIX_ST170_M]
MATRIX_ST240_M: Literal[MatrixCoefficients.MATRIX_ST240_M]
MATRIX_YCGCO: Literal[MatrixCoefficients.MATRIX_YCGCO]
MATRIX_BT2020_NCL: Literal[MatrixCoefficients.MATRIX_BT2020_NCL]
MATRIX_BT2020_CL: Literal[MatrixCoefficients.MATRIX_BT2020_CL]
MATRIX_CHROMATICITY_DERIVED_NCL: Literal[MatrixCoefficients.MATRIX_CHROMATICITY_DERIVED_NCL]
MATRIX_CHROMATICITY_DERIVED_CL: Literal[MatrixCoefficients.MATRIX_CHROMATICITY_DERIVED_CL]
MATRIX_ICTCP: Literal[MatrixCoefficients.MATRIX_ICTCP]

class TransferCharacteristics(IntEnum):
    TRANSFER_BT709 = ...
    TRANSFER_UNSPECIFIED = ...
    TRANSFER_BT470_M = ...
    TRANSFER_BT470_BG = ...
    TRANSFER_BT601 = ...
    TRANSFER_ST240_M = ...
    TRANSFER_LINEAR = ...
    TRANSFER_LOG_100 = ...
    TRANSFER_LOG_316 = ...
    TRANSFER_IEC_61966_2_4 = ...
    TRANSFER_IEC_61966_2_1 = ...
    TRANSFER_BT2020_10 = ...
    TRANSFER_BT2020_12 = ...
    TRANSFER_ST2084 = ...
    TRANSFER_ST428 = ...
    TRANSFER_ARIB_B67 = ...

TRANSFER_BT709: Literal[TransferCharacteristics.TRANSFER_BT709]
TRANSFER_UNSPECIFIED: Literal[TransferCharacteristics.TRANSFER_UNSPECIFIED]
TRANSFER_BT470_M: Literal[TransferCharacteristics.TRANSFER_BT470_M]
TRANSFER_BT470_BG: Literal[TransferCharacteristics.TRANSFER_BT470_BG]
TRANSFER_BT601: Literal[TransferCharacteristics.TRANSFER_BT601]
TRANSFER_ST240_M: Literal[TransferCharacteristics.TRANSFER_ST240_M]
TRANSFER_LINEAR: Literal[TransferCharacteristics.TRANSFER_LINEAR]
TRANSFER_LOG_100: Literal[TransferCharacteristics.TRANSFER_LOG_100]
TRANSFER_LOG_316: Literal[TransferCharacteristics.TRANSFER_LOG_316]
TRANSFER_IEC_61966_2_4: Literal[TransferCharacteristics.TRANSFER_IEC_61966_2_4]
TRANSFER_IEC_61966_2_1: Literal[TransferCharacteristics.TRANSFER_IEC_61966_2_1]
TRANSFER_BT2020_10: Literal[TransferCharacteristics.TRANSFER_BT2020_10]
TRANSFER_BT2020_12: Literal[TransferCharacteristics.TRANSFER_BT2020_12]
TRANSFER_ST2084: Literal[TransferCharacteristics.TRANSFER_ST2084]
TRANSFER_ST428: Literal[TransferCharacteristics.TRANSFER_ST428]
TRANSFER_ARIB_B67: Literal[TransferCharacteristics.TRANSFER_ARIB_B67]

class ColorPrimaries(IntEnum):
    PRIMARIES_BT709 = ...
    PRIMARIES_UNSPECIFIED = ...
    PRIMARIES_BT470_M = ...
    PRIMARIES_BT470_BG = ...
    PRIMARIES_ST170_M = ...
    PRIMARIES_ST240_M = ...
    PRIMARIES_FILM = ...
    PRIMARIES_BT2020 = ...
    PRIMARIES_ST428 = ...
    PRIMARIES_ST431_2 = ...
    PRIMARIES_ST432_1 = ...
    PRIMARIES_EBU3213_E = ...

PRIMARIES_BT709: Literal[ColorPrimaries.PRIMARIES_BT709]
PRIMARIES_UNSPECIFIED: Literal[ColorPrimaries.PRIMARIES_UNSPECIFIED]
PRIMARIES_BT470_M: Literal[ColorPrimaries.PRIMARIES_BT470_M]
PRIMARIES_BT470_BG: Literal[ColorPrimaries.PRIMARIES_BT470_BG]
PRIMARIES_ST170_M: Literal[ColorPrimaries.PRIMARIES_ST170_M]
PRIMARIES_ST240_M: Literal[ColorPrimaries.PRIMARIES_ST240_M]
PRIMARIES_FILM: Literal[ColorPrimaries.PRIMARIES_FILM]
PRIMARIES_BT2020: Literal[ColorPrimaries.PRIMARIES_BT2020]
PRIMARIES_ST428: Literal[ColorPrimaries.PRIMARIES_ST428]
PRIMARIES_ST431_2: Literal[ColorPrimaries.PRIMARIES_ST431_2]
PRIMARIES_ST432_1: Literal[ColorPrimaries.PRIMARIES_ST432_1]
PRIMARIES_EBU3213_E: Literal[ColorPrimaries.PRIMARIES_EBU3213_E]

class _VideoFormatDict(TypedDict):
    id: int
    name: str
    color_family: ColorFamily
    sample_type: SampleType
    bits_per_sample: Literal[
        8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
    ]
    bytes_per_sample: int
    subsampling_w: Literal[0, 1, 2, 3, 4]
    subsampling_h: Literal[0, 1, 2, 3, 4]
    num_planes: Literal[1, 3]

class VideoFormat:
    id: Final[int]
    name: Final[str]
    color_family: Final[ColorFamily]
    sample_type: Final[SampleType]
    bits_per_sample: Final[
        Literal[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
    ]
    bytes_per_sample: Final[int]
    subsampling_w: Final[Literal[0, 1, 2, 3, 4]]
    subsampling_h: Final[Literal[0, 1, 2, 3, 4]]
    num_planes: Final[Literal[1, 3]]
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def replace(
        self,
        *,
        color_family: ColorFamily = ...,
        sample_type: SampleType = ...,
        bits_per_sample: SupportsInt = ...,
        subsampling_w: SupportsInt = ...,
        subsampling_h: SupportsInt = ...,
    ) -> Self: ...
    def _as_dict(self) -> _VideoFormatDict: ...

# Behave like a Collection
class ChannelLayout(int):
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __contains__(self, layout: AudioChannels) -> bool: ...
    def __iter__(self) -> Iterator[AudioChannels]: ...
    def __len__(self) -> int: ...

type _PropValue = (
    int
    | float
    | str
    | bytes
    | RawFrame
    | VideoFrame
    | AudioFrame
    | RawNode
    | VideoNode
    | AudioNode
    | Callable[..., Any]
    | list[int]
    | list[float]
    | list[str]
    | list[bytes]
    | list[RawFrame]
    | list[VideoFrame]
    | list[AudioFrame]
    | list[RawNode]
    | list[VideoNode]
    | list[AudioNode]
    | list[Callable[..., Any]]
)

# Only the _PropValue types are allowed in FrameProps but passing _VSValue is allowed.
# Just keep in mind that _SupportsIter and _GetItemIterable will only yield their keys if they're Mapping-like.
# Consider storing Mapping-likes as two separate props. One for the keys and one for the values as list.
class FrameProps(MutableMapping[str, _PropValue]):
    def __repr__(self) -> str: ...
    def __dir__(self) -> list[str]: ...
    def __getitem__(self, name: str) -> _PropValue: ...
    def __setitem__(self, name: str, value: _VSValue) -> None: ...
    def __delitem__(self, name: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __setattr__(self, name: str, value: _VSValue) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __getattr__(self, name: str) -> _PropValue: ...
    @overload
    def setdefault(self, key: str, default: Literal[0] = 0, /) -> _PropValue | Literal[0]: ...
    @overload
    def setdefault(self, key: str, default: _VSValue, /) -> _PropValue: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def copy(self) -> dict[str, _PropValue]: ...

class FuncData:
    def __call__(self, **kwargs: Any) -> Any: ...

class Func:
    def __call__(self, **kwargs: Any) -> Any: ...

class Function:
    plugin: Final[Plugin]
    name: Final[str]
    signature: Final[str]
    return_signature: Final[str]
    def __repr__(self) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    @property
    def __signature__(self) -> Signature: ...

class PluginVersion(NamedTuple):
    major: int
    minor: int

class Plugin:
    identifier: Final[str]
    namespace: Final[str]
    name: Final[str]

    def __repr__(self) -> str: ...
    def __dir__(self) -> list[str]: ...
    def __getattr__(self, name: str) -> Function: ...
    @property
    def version(self) -> PluginVersion: ...
    @property
    def plugin_path(self) -> str: ...
    def functions(self) -> Iterator[Function]: ...

_VSPlugin = Plugin
_VSFunction = Function

class _Wrapper:
    class Function[**_P, _R](_VSFunction):
        def __init__[_PluginT: Plugin](self, function: Callable[Concatenate[_PluginT, _P], _R]) -> None: ...
        def __call__(self, *args: _P.args, **kwargs: _P.kwargs) -> _R: ...

class FramePtr: ...

# These memoryview-likes don't exist at runtime.
class _video_view(memoryview):  # type: ignore[misc]
    def __getitem__(self, index: tuple[int, int]) -> int | float: ...  # type: ignore[override]
    def __setitem__(self, index: tuple[int, int], other: int | float) -> None: ...  # type: ignore[override]
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def strides(self) -> tuple[int, int]: ...
    @property
    def ndim(self) -> Literal[2]: ...
    @property
    def obj(self) -> FramePtr: ...  # type: ignore[override]
    def tolist(self) -> list[int | float]: ...  # type: ignore[override]

class _audio_view(memoryview):  # type: ignore[misc]
    def __getitem__(self, index: int) -> int | float: ...  # type: ignore[override]
    def __setitem__(self, index: int, other: int | float) -> None: ...  # type: ignore[override]
    @property
    def shape(self) -> tuple[int]: ...
    @property
    def strides(self) -> tuple[int]: ...
    @property
    def ndim(self) -> Literal[1]: ...
    @property
    def obj(self) -> FramePtr: ...  # type: ignore[override]
    def tolist(self) -> list[int | float]: ...  # type: ignore[override]

class RawFrame:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc: type[BaseException] | None = None, val: BaseException | None = None, tb: TracebackType | None = None
    ) -> bool | None: ...
    def __getitem__(self, index: SupportsInt) -> memoryview: ...
    def __len__(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def props(self) -> FrameProps: ...
    @props.setter
    def props(self, new_props: _SupportsKeysAndGetItem[str, _VSValue]) -> None: ...
    @property
    def readonly(self) -> bool: ...
    def copy(self) -> Self: ...
    def close(self) -> None: ...
    def get_write_ptr(self, plane: SupportsInt) -> c_void_p: ...
    def get_read_ptr(self, plane: SupportsInt) -> c_void_p: ...
    def get_stride(self, plane: SupportsInt) -> int: ...

# Behave like a Sequence
class VideoFrame(RawFrame):
    format: Final[VideoFormat]
    width: Final[int]
    height: Final[int]

    def __getitem__(self, index: SupportsInt) -> _video_view: ...
    def readchunks(self) -> Iterator[_video_view]: ...

# Behave like a Sequence
class AudioFrame(RawFrame):
    sample_type: Final[SampleType]
    bits_per_sample: Final[int]
    bytes_per_sample: Final[int]
    channel_layout: Final[int]
    num_channels: Final[int]

    def __getitem__(self, index: SupportsInt) -> _audio_view: ...
    @property
    def channels(self) -> ChannelLayout: ...

class RawNode:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __dir__(self) -> list[str]: ...
    def __getitem__(self, index: int | slice[int | None, int | None, int | None]) -> Self: ...
    def __len__(self) -> int: ...
    def __add__(self, other: Self) -> Self: ...
    def __mul__(self, other: int) -> Self: ...
    def __getattr__(self, name: str) -> Plugin: ...
    @property
    def node_name(self) -> str: ...
    @property
    def timings(self) -> int: ...
    @timings.setter
    def timings(self, value: Literal[0]) -> None: ...
    @property
    def mode(self) -> FilterMode: ...
    @property
    def dependencies(self) -> tuple[Self, ...]: ...
    @property
    def _name(self) -> str: ...
    @property
    def _inputs(self) -> dict[str, _VSValue]: ...
    def get_frame(self, n: SupportsInt) -> RawFrame: ...
    @overload
    def get_frame_async(self, n: SupportsInt) -> Future[RawFrame]: ...
    @overload
    def get_frame_async(self, n: SupportsInt, cb: Callable[[RawFrame | None, Exception | None], None]) -> None: ...
    def frames(
        self, prefetch: int | None = None, backlog: int | None = None, close: bool = False
    ) -> Iterator[RawFrame]: ...
    def set_output(self, index: SupportsInt = 0) -> None: ...
    def clear_cache(self) -> None: ...
    def is_inspectable(self, version: int | None = None) -> bool: ...

type _CurrentFrame = int
type _TotalFrames = int

# Behave like a Sequence
class VideoNode(RawNode):
    format: Final[VideoFormat]
    width: Final[int]
    height: Final[int]
    num_frames: Final[int]
    fps_num: Final[int]
    fps_den: Final[int]
    fps: Final[Fraction]
    def get_frame(self, n: SupportsInt) -> VideoFrame: ...
    @overload  # type: ignore[override]
    def get_frame_async(self, n: SupportsInt) -> Future[VideoFrame]: ...
    @overload
    def get_frame_async(self, n: SupportsInt, cb: Callable[[VideoFrame | None, Exception | None], None]) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def frames(
        self, prefetch: int | None = None, backlog: int | None = None, close: bool = False
    ) -> Iterator[VideoFrame]: ...
    def set_output(
        self, index: SupportsInt = 0, alpha: Self | None = None, alt_output: Literal[0, 1, 2] = 0
    ) -> None: ...
    def output(
        self,
        fileobj: IO[bytes],
        y4m: bool = False,
        progress_update: Callable[[_CurrentFrame, _TotalFrames], None] | None = None,
        prefetch: int = 0,
        backlog: int = -1,
    ) -> None: ...

# <plugins/bound/VideoNode>
# <attribute/VideoNode_bound/akarin>
    akarin: Final[_akarin._VideoNode_bound.Plugin]
    """Akarin's Experimental Filters"""
# </attribute/VideoNode_bound/akarin>
# <attribute/VideoNode_bound/ocr>
    ocr: Final[_ocr._VideoNode_bound.Plugin]
    """Tesseract OCR Filter"""
# </attribute/VideoNode_bound/ocr>
# <attribute/VideoNode_bound/resize>
    resize: Final[_resize._VideoNode_bound.Plugin]
    """VapourSynth Resize"""
# </attribute/VideoNode_bound/resize>
# <attribute/VideoNode_bound/std>
    std: Final[_std._VideoNode_bound.Plugin]
    """VapourSynth Core Functions"""
# </attribute/VideoNode_bound/std>
# <attribute/VideoNode_bound/zsmooth>
    zsmooth: Final[_zsmooth._VideoNode_bound.Plugin]
    """Smoothing functions in Zig"""
# </attribute/VideoNode_bound/zsmooth>
# </plugins/bound/VideoNode>

# Behave like a Sequence
class AudioNode(RawNode):
    sample_type: Final[SampleType]
    bits_per_sample: Final[int]
    bytes_per_sample: Final[int]
    channel_layout: Final[int]
    num_channels: Final[int]
    sample_rate: Final[int]
    num_samples: Final[int]
    num_frames: Final[int]
    @property
    def channels(self) -> ChannelLayout: ...
    def get_frame(self, n: SupportsInt) -> AudioFrame: ...
    @overload  # type: ignore[override]
    def get_frame_async(self, n: SupportsInt) -> Future[AudioFrame]: ...
    @overload
    def get_frame_async(self, n: SupportsInt, cb: Callable[[AudioFrame | None, Exception | None], None]) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def frames(
        self, prefetch: int | None = None, backlog: int | None = None, close: bool = False
    ) -> Iterator[AudioFrame]: ...

# <plugins/bound/AudioNode>
# <attribute/AudioNode_bound/std>
    std: Final[_std._AudioNode_bound.Plugin]
    """VapourSynth Core Functions"""
# </attribute/AudioNode_bound/std>
# </plugins/bound/AudioNode>

class Core:
    timings: Final[CoreTimings]
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __dir__(self) -> list[str]: ...
    def __getattr__(self, name: str) -> Plugin: ...
    @property
    def api_version(self) -> VapourSynthAPIVersion: ...
    @property
    def core_version(self) -> VapourSynthVersion: ...
    @property
    def num_threads(self) -> int: ...
    @num_threads.setter
    def num_threads(self, value: SupportsInt) -> None: ...
    @property
    def max_cache_size(self) -> int: ...
    @max_cache_size.setter
    def max_cache_size(self, mb: SupportsInt) -> None: ...
    @property
    def used_cache_size(self) -> int: ...
    @property
    def flags(self) -> int: ...
    def plugins(self) -> Iterator[Plugin]: ...
    def query_video_format(
        self,
        color_family: SupportsInt,
        sample_type: SupportsInt,
        bits_per_sample: SupportsInt,
        subsampling_w: SupportsInt = 0,
        subsampling_h: SupportsInt = 0,
    ) -> VideoFormat: ...
    def get_video_format(self, id: SupportsInt) -> VideoFormat: ...
    def create_video_frame(self, format: VideoFormat, width: SupportsInt, height: SupportsInt) -> VideoFrame: ...
    def log_message(self, message_type: SupportsInt, message: str) -> None: ...
    def add_log_handler(self, handler_func: Callable[[MessageType, str], None]) -> LogHandle: ...
    def remove_log_handler(self, handle: LogHandle) -> None: ...
    def clear_cache(self) -> None: ...
    @deprecated("core.version() is deprecated, use str(core)!", category=DeprecationWarning)
    def version(self) -> str: ...
    @deprecated(
        "core.version_number() is deprecated, use core.core_version.release_major!", category=DeprecationWarning
    )
    def version_number(self) -> int: ...

# <plugins/bound/Core>
# <attribute/Core_bound/akarin>
    akarin: Final[_akarin._Core_bound.Plugin]
    """Akarin's Experimental Filters"""
# </attribute/Core_bound/akarin>
# <attribute/Core_bound/ffms2>
    ffms2: Final[_ffms2._Core_bound.Plugin]
    """FFmpegSource 2 for VapourSynth"""
# </attribute/Core_bound/ffms2>
# <attribute/Core_bound/ocr>
    ocr: Final[_ocr._Core_bound.Plugin]
    """Tesseract OCR Filter"""
# </attribute/Core_bound/ocr>
# <attribute/Core_bound/resize>
    resize: Final[_resize._Core_bound.Plugin]
    """VapourSynth Resize"""
# </attribute/Core_bound/resize>
# <attribute/Core_bound/std>
    std: Final[_std._Core_bound.Plugin]
    """VapourSynth Core Functions"""
# </attribute/Core_bound/std>
# <attribute/Core_bound/zsmooth>
    zsmooth: Final[_zsmooth._Core_bound.Plugin]
    """Smoothing functions in Zig"""
# </attribute/Core_bound/zsmooth>
# </plugins/bound/Core>

# _CoreProxy doesn't inherit from Core but __getattr__ returns the attribute from the actual core
class _CoreProxy(Core):
    def __setattr__(self, name: str, value: Any) -> None: ...
    @property
    def core(self) -> Core: ...

core: _CoreProxy

# <plugins/implementations>
# <implementation/akarin>
_ReturnDict_akarin_Version = TypedDict("_ReturnDict_akarin_Version", {"version": _AnyStr, "expr_backend": _AnyStr, "expr_features": _AnyStr | list[_AnyStr], "select_features": _AnyStr | list[_AnyStr], "text_features": _AnyStr | list[_AnyStr], "tmpl_features": _AnyStr | list[_AnyStr]})

class _akarin:
    class _Core_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def Cambi(self, clip: VideoNode, window_size: int | None = None, topk: float | None = None, tvi_threshold: float | None = None, scores: int | None = None, scaling: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DLISR(self, clip: VideoNode, scale: int | None = None, device_id: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DLVFX(self, clip: VideoNode, op: int, scale: float | None = None, strength: float | None = None, output_depth: int | None = None, num_streams: int | None = None, model_dir: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Expr(self, clips: VideoNode | _SequenceLike[VideoNode], expr: _AnyStr | _SequenceLike[_AnyStr], format: int | None = None, opt: int | None = None, boundary: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PropExpr(self, clips: VideoNode | _SequenceLike[VideoNode], dict: Func | _VSCallback_akarin_PropExpr_dict) -> VideoNode: ...
            @_Wrapper.Function
            def Select(self, clip_src: VideoNode | _SequenceLike[VideoNode], prop_src: VideoNode | _SequenceLike[VideoNode], expr: _AnyStr | _SequenceLike[_AnyStr]) -> VideoNode: ...
            @_Wrapper.Function
            def Text(self, clips: VideoNode | _SequenceLike[VideoNode], text: _AnyStr, alignment: int | None = None, scale: int | None = None, prop: _AnyStr | None = None, strict: int | None = None, vspipe: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Tmpl(self, clips: VideoNode | _SequenceLike[VideoNode], prop: _AnyStr | _SequenceLike[_AnyStr], text: _AnyStr | _SequenceLike[_AnyStr]) -> VideoNode: ...
            @_Wrapper.Function
            def Version(self) -> _ReturnDict_akarin_Version: ...

    class _VideoNode_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def Cambi(self, window_size: int | None = None, topk: float | None = None, tvi_threshold: float | None = None, scores: int | None = None, scaling: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DLISR(self, scale: int | None = None, device_id: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DLVFX(self, op: int, scale: float | None = None, strength: float | None = None, output_depth: int | None = None, num_streams: int | None = None, model_dir: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Expr(self, expr: _AnyStr | _SequenceLike[_AnyStr], format: int | None = None, opt: int | None = None, boundary: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PropExpr(self, dict: Func | _VSCallback_akarin_PropExpr_dict) -> VideoNode: ...
            @_Wrapper.Function
            def Select(self, prop_src: VideoNode | _SequenceLike[VideoNode], expr: _AnyStr | _SequenceLike[_AnyStr]) -> VideoNode: ...
            @_Wrapper.Function
            def Text(self, text: _AnyStr, alignment: int | None = None, scale: int | None = None, prop: _AnyStr | None = None, strict: int | None = None, vspipe: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Tmpl(self, prop: _AnyStr | _SequenceLike[_AnyStr], text: _AnyStr | _SequenceLike[_AnyStr]) -> VideoNode: ...

# </implementation/akarin>

# <implementation/ffms2>
class _ffms2:
    class _Core_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def GetLogLevel(self) -> int: ...
            @_Wrapper.Function
            def Index(self, source: _AnyStr, cachefile: _AnyStr | None = None, indextracks: int | _SequenceLike[int] | None = None, errorhandling: int | None = None, overwrite: int | None = None, enable_drefs: int | None = None, use_absolute_path: int | None = None) -> _AnyStr: ...
            @_Wrapper.Function
            def SetLogLevel(self, level: int) -> int: ...
            @_Wrapper.Function
            def Source(self, source: _AnyStr, track: int | None = None, cache: int | None = None, cachefile: _AnyStr | None = None, fpsnum: int | None = None, fpsden: int | None = None, threads: int | None = None, timecodes: _AnyStr | None = None, seekmode: int | None = None, width: int | None = None, height: int | None = None, resizer: _AnyStr | None = None, format: int | None = None, alpha: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Version(self) -> _AnyStr: ...

# </implementation/ffms2>

# <implementation/ocr>
class _ocr:
    class _Core_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def Recognize(self, clip: VideoNode, datapath: _AnyStr | None = None, language: _AnyStr | None = None, options: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...

    class _VideoNode_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def Recognize(self, datapath: _AnyStr | None = None, language: _AnyStr | None = None, options: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...

# </implementation/ocr>

# <implementation/resize>
class _resize:
    class _Core_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def Bicubic(self, clip: VideoNode, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Bilinear(self, clip: VideoNode, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Bob(self, clip: VideoNode, filter: _AnyStr | None = None, tff: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Lanczos(self, clip: VideoNode, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Point(self, clip: VideoNode, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Spline16(self, clip: VideoNode, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Spline36(self, clip: VideoNode, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Spline64(self, clip: VideoNode, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...

    class _VideoNode_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def Bicubic(self, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Bilinear(self, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Bob(self, filter: _AnyStr | None = None, tff: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Lanczos(self, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Point(self, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Spline16(self, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Spline36(self, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Spline64(self, width: int | None = None, height: int | None = None, format: int | None = None, matrix: int | None = None, matrix_s: _AnyStr | None = None, transfer: int | None = None, transfer_s: _AnyStr | None = None, primaries: int | None = None, primaries_s: _AnyStr | None = None, range: int | None = None, range_s: _AnyStr | None = None, chromaloc: int | None = None, chromaloc_s: _AnyStr | None = None, matrix_in: int | None = None, matrix_in_s: _AnyStr | None = None, transfer_in: int | None = None, transfer_in_s: _AnyStr | None = None, primaries_in: int | None = None, primaries_in_s: _AnyStr | None = None, range_in: int | None = None, range_in_s: _AnyStr | None = None, chromaloc_in: int | None = None, chromaloc_in_s: _AnyStr | None = None, filter_param_a: float | None = None, filter_param_b: float | None = None, resample_filter_uv: _AnyStr | None = None, filter_param_a_uv: float | None = None, filter_param_b_uv: float | None = None, dither_type: _AnyStr | None = None, cpu_type: _AnyStr | None = None, prefer_props: int | None = None, src_left: float | None = None, src_top: float | None = None, src_width: float | None = None, src_height: float | None = None, nominal_luminance: float | None = None, approximate_gamma: int | None = None) -> VideoNode: ...

# </implementation/resize>

# <implementation/std>
class _std:
    class _Core_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def AddBorders(self, clip: VideoNode, left: int | None = None, right: int | None = None, top: int | None = None, bottom: int | None = None, color: float | _SequenceLike[float] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def AssumeFPS(self, clip: VideoNode, src: VideoNode | None = None, fpsnum: int | None = None, fpsden: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def AssumeSampleRate(self, clip: AudioNode, src: AudioNode | None = None, samplerate: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioGain(self, clip: AudioNode, gain: float | _SequenceLike[float] | None = None, overflow_error: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioLoop(self, clip: AudioNode, times: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioMix(self, clips: AudioNode | _SequenceLike[AudioNode], matrix: float | _SequenceLike[float], channels_out: int | _SequenceLike[int], overflow_error: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioReverse(self, clip: AudioNode) -> AudioNode: ...
            @_Wrapper.Function
            def AudioSplice(self, clips: AudioNode | _SequenceLike[AudioNode]) -> AudioNode: ...
            @_Wrapper.Function
            def AudioTrim(self, clip: AudioNode, first: int | None = None, last: int | None = None, length: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AverageFrames(self, clips: VideoNode | _SequenceLike[VideoNode], weights: float | _SequenceLike[float], scale: float | None = None, scenechange: int | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Binarize(self, clip: VideoNode, threshold: float | _SequenceLike[float] | None = None, v0: float | _SequenceLike[float] | None = None, v1: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def BinarizeMask(self, clip: VideoNode, threshold: float | _SequenceLike[float] | None = None, v0: float | _SequenceLike[float] | None = None, v1: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def BlankAudio(self, clip: AudioNode | None = None, channels: int | _SequenceLike[int] | None = None, bits: int | None = None, sampletype: int | None = None, samplerate: int | None = None, length: int | None = None, keep: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def BlankClip(self, clip: VideoNode | None = None, width: int | None = None, height: int | None = None, format: int | None = None, length: int | None = None, fpsnum: int | None = None, fpsden: int | None = None, color: float | _SequenceLike[float] | None = None, keep: int | None = None, varsize: int | None = None, varformat: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def BoxBlur(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, hradius: int | None = None, hpasses: int | None = None, vradius: int | None = None, vpasses: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Cache(self, clip: VideoNode, size: int | None = None, fixed: int | None = None, make_linear: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def ClipToProp(self, clip: VideoNode, mclip: VideoNode, prop: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Convolution(self, clip: VideoNode, matrix: float | _SequenceLike[float], bias: float | None = None, divisor: float | None = None, planes: int | _SequenceLike[int] | None = None, saturate: int | None = None, mode: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CopyFrameProps(self, clip: VideoNode, prop_src: VideoNode, props: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Crop(self, clip: VideoNode, left: int | None = None, right: int | None = None, top: int | None = None, bottom: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CropAbs(self, clip: VideoNode, width: int, height: int, left: int | None = None, top: int | None = None, x: int | None = None, y: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CropRel(self, clip: VideoNode, left: int | None = None, right: int | None = None, top: int | None = None, bottom: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Deflate(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DeleteFrames(self, clip: VideoNode, frames: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def DoubleWeave(self, clip: VideoNode, tff: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DuplicateFrames(self, clip: VideoNode, frames: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def Expr(self, clips: VideoNode | _SequenceLike[VideoNode], expr: _AnyStr | _SequenceLike[_AnyStr], format: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FlipHorizontal(self, clip: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def FlipVertical(self, clip: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def FrameEval(self, clip: VideoNode, eval: Func | _VSCallback_std_FrameEval_eval, prop_src: VideoNode | _SequenceLike[VideoNode] | None = None, clip_src: VideoNode | _SequenceLike[VideoNode] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FreezeFrames(self, clip: VideoNode, first: int | _SequenceLike[int] | None = None, last: int | _SequenceLike[int] | None = None, replacement: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Inflate(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Interleave(self, clips: VideoNode | _SequenceLike[VideoNode], extend: int | None = None, mismatch: int | None = None, modify_duration: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Invert(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def InvertMask(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Levels(self, clip: VideoNode, min_in: float | _SequenceLike[float] | None = None, max_in: float | _SequenceLike[float] | None = None, gamma: float | _SequenceLike[float] | None = None, min_out: float | _SequenceLike[float] | None = None, max_out: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Limiter(self, clip: VideoNode, min: float | _SequenceLike[float] | None = None, max: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def LoadAllPlugins(self, path: _AnyStr) -> None: ...
            @_Wrapper.Function
            def LoadPlugin(self, path: _AnyStr, altsearchpath: int | None = None, forcens: _AnyStr | None = None, forceid: _AnyStr | None = None) -> None: ...
            @_Wrapper.Function
            def Loop(self, clip: VideoNode, times: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Lut(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, lut: int | _SequenceLike[int] | None = None, lutf: float | _SequenceLike[float] | None = None, function: Func | _VSCallback_std_Lut_function | None = None, bits: int | None = None, floatout: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Lut2(self, clipa: VideoNode, clipb: VideoNode, planes: int | _SequenceLike[int] | None = None, lut: int | _SequenceLike[int] | None = None, lutf: float | _SequenceLike[float] | None = None, function: Func | _VSCallback_std_Lut2_function | None = None, bits: int | None = None, floatout: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MakeDiff(self, clipa: VideoNode, clipb: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MakeFullDiff(self, clipa: VideoNode, clipb: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def MaskedMerge(self, clipa: VideoNode, clipb: VideoNode, mask: VideoNode, planes: int | _SequenceLike[int] | None = None, first_plane: int | None = None, premultiplied: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Maximum(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None, coordinates: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Median(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Merge(self, clipa: VideoNode, clipb: VideoNode, weight: float | _SequenceLike[float] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MergeDiff(self, clipa: VideoNode, clipb: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MergeFullDiff(self, clipa: VideoNode, clipb: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def Minimum(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None, coordinates: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def ModifyFrame(self, clip: VideoNode, clips: VideoNode | _SequenceLike[VideoNode], selector: Func | _VSCallback_std_ModifyFrame_selector) -> VideoNode: ...
            @_Wrapper.Function
            def PEMVerifier(self, clip: VideoNode, upper: float | _SequenceLike[float] | None = None, lower: float | _SequenceLike[float] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PlaneStats(self, clipa: VideoNode, clipb: VideoNode | None = None, plane: int | None = None, prop: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PreMultiply(self, clip: VideoNode, alpha: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def Prewitt(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, scale: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PropToClip(self, clip: VideoNode, prop: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def RemoveFrameProps(self, clip: VideoNode, props: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Reverse(self, clip: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def SelectEvery(self, clip: VideoNode, cycle: int, offsets: int | _SequenceLike[int], modify_duration: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SeparateFields(self, clip: VideoNode, tff: int | None = None, modify_duration: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SetAudioCache(self, clip: AudioNode, mode: int | None = None, fixedsize: int | None = None, maxsize: int | None = None, maxhistory: int | None = None) -> None: ...
            @_Wrapper.Function
            def SetFieldBased(self, clip: VideoNode, value: int) -> VideoNode: ...
            @_Wrapper.Function
            def SetFrameProp(self, clip: VideoNode, prop: _AnyStr, intval: int | _SequenceLike[int] | None = None, floatval: float | _SequenceLike[float] | None = None, data: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SetFrameProps(self, clip: VideoNode, **kwargs: Any) -> VideoNode: ...
            @_Wrapper.Function
            def SetMaxCPU(self, cpu: _AnyStr) -> _AnyStr: ...
            @_Wrapper.Function
            def SetVideoCache(self, clip: VideoNode, mode: int | None = None, fixedsize: int | None = None, maxsize: int | None = None, maxhistory: int | None = None) -> None: ...
            @_Wrapper.Function
            def ShuffleChannels(self, clips: AudioNode | _SequenceLike[AudioNode], channels_in: int | _SequenceLike[int], channels_out: int | _SequenceLike[int]) -> AudioNode: ...
            @_Wrapper.Function
            def ShufflePlanes(self, clips: VideoNode | _SequenceLike[VideoNode], planes: int | _SequenceLike[int], colorfamily: int, prop_src: VideoNode | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Sobel(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None, scale: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Splice(self, clips: VideoNode | _SequenceLike[VideoNode], mismatch: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SplitChannels(self, clip: AudioNode) -> AudioNode | list[AudioNode]: ...
            @_Wrapper.Function
            def SplitPlanes(self, clip: VideoNode) -> VideoNode | list[VideoNode]: ...
            @_Wrapper.Function
            def StackHorizontal(self, clips: VideoNode | _SequenceLike[VideoNode]) -> VideoNode: ...
            @_Wrapper.Function
            def StackVertical(self, clips: VideoNode | _SequenceLike[VideoNode]) -> VideoNode: ...
            @_Wrapper.Function
            def TestAudio(self, channels: int | _SequenceLike[int] | None = None, bits: int | None = None, isfloat: int | None = None, samplerate: int | None = None, length: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def Transpose(self, clip: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def Trim(self, clip: VideoNode, first: int | None = None, last: int | None = None, length: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Turn180(self, clip: VideoNode) -> VideoNode: ...

    class _VideoNode_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def AddBorders(self, left: int | None = None, right: int | None = None, top: int | None = None, bottom: int | None = None, color: float | _SequenceLike[float] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def AssumeFPS(self, src: VideoNode | None = None, fpsnum: int | None = None, fpsden: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def AverageFrames(self, weights: float | _SequenceLike[float], scale: float | None = None, scenechange: int | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Binarize(self, threshold: float | _SequenceLike[float] | None = None, v0: float | _SequenceLike[float] | None = None, v1: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def BinarizeMask(self, threshold: float | _SequenceLike[float] | None = None, v0: float | _SequenceLike[float] | None = None, v1: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def BlankClip(self, width: int | None = None, height: int | None = None, format: int | None = None, length: int | None = None, fpsnum: int | None = None, fpsden: int | None = None, color: float | _SequenceLike[float] | None = None, keep: int | None = None, varsize: int | None = None, varformat: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def BoxBlur(self, planes: int | _SequenceLike[int] | None = None, hradius: int | None = None, hpasses: int | None = None, vradius: int | None = None, vpasses: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Cache(self, size: int | None = None, fixed: int | None = None, make_linear: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def ClipToProp(self, mclip: VideoNode, prop: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Convolution(self, matrix: float | _SequenceLike[float], bias: float | None = None, divisor: float | None = None, planes: int | _SequenceLike[int] | None = None, saturate: int | None = None, mode: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CopyFrameProps(self, prop_src: VideoNode, props: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Crop(self, left: int | None = None, right: int | None = None, top: int | None = None, bottom: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CropAbs(self, width: int, height: int, left: int | None = None, top: int | None = None, x: int | None = None, y: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CropRel(self, left: int | None = None, right: int | None = None, top: int | None = None, bottom: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Deflate(self, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DeleteFrames(self, frames: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def DoubleWeave(self, tff: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DuplicateFrames(self, frames: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def Expr(self, expr: _AnyStr | _SequenceLike[_AnyStr], format: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FlipHorizontal(self) -> VideoNode: ...
            @_Wrapper.Function
            def FlipVertical(self) -> VideoNode: ...
            @_Wrapper.Function
            def FrameEval(self, eval: Func | _VSCallback_std_FrameEval_eval, prop_src: VideoNode | _SequenceLike[VideoNode] | None = None, clip_src: VideoNode | _SequenceLike[VideoNode] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FreezeFrames(self, first: int | _SequenceLike[int] | None = None, last: int | _SequenceLike[int] | None = None, replacement: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Inflate(self, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Interleave(self, extend: int | None = None, mismatch: int | None = None, modify_duration: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Invert(self, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def InvertMask(self, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Levels(self, min_in: float | _SequenceLike[float] | None = None, max_in: float | _SequenceLike[float] | None = None, gamma: float | _SequenceLike[float] | None = None, min_out: float | _SequenceLike[float] | None = None, max_out: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Limiter(self, min: float | _SequenceLike[float] | None = None, max: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Loop(self, times: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Lut(self, planes: int | _SequenceLike[int] | None = None, lut: int | _SequenceLike[int] | None = None, lutf: float | _SequenceLike[float] | None = None, function: Func | _VSCallback_std_Lut_function | None = None, bits: int | None = None, floatout: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Lut2(self, clipb: VideoNode, planes: int | _SequenceLike[int] | None = None, lut: int | _SequenceLike[int] | None = None, lutf: float | _SequenceLike[float] | None = None, function: Func | _VSCallback_std_Lut2_function | None = None, bits: int | None = None, floatout: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MakeDiff(self, clipb: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MakeFullDiff(self, clipb: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def MaskedMerge(self, clipb: VideoNode, mask: VideoNode, planes: int | _SequenceLike[int] | None = None, first_plane: int | None = None, premultiplied: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Maximum(self, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None, coordinates: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Median(self, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Merge(self, clipb: VideoNode, weight: float | _SequenceLike[float] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MergeDiff(self, clipb: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def MergeFullDiff(self, clipb: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def Minimum(self, planes: int | _SequenceLike[int] | None = None, threshold: float | None = None, coordinates: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def ModifyFrame(self, clips: VideoNode | _SequenceLike[VideoNode], selector: Func | _VSCallback_std_ModifyFrame_selector) -> VideoNode: ...
            @_Wrapper.Function
            def PEMVerifier(self, upper: float | _SequenceLike[float] | None = None, lower: float | _SequenceLike[float] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PlaneStats(self, clipb: VideoNode | None = None, plane: int | None = None, prop: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PreMultiply(self, alpha: VideoNode) -> VideoNode: ...
            @_Wrapper.Function
            def Prewitt(self, planes: int | _SequenceLike[int] | None = None, scale: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def PropToClip(self, prop: _AnyStr | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def RemoveFrameProps(self, props: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Reverse(self) -> VideoNode: ...
            @_Wrapper.Function
            def SelectEvery(self, cycle: int, offsets: int | _SequenceLike[int], modify_duration: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SeparateFields(self, tff: int | None = None, modify_duration: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SetFieldBased(self, value: int) -> VideoNode: ...
            @_Wrapper.Function
            def SetFrameProp(self, prop: _AnyStr, intval: int | _SequenceLike[int] | None = None, floatval: float | _SequenceLike[float] | None = None, data: _AnyStr | _SequenceLike[_AnyStr] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SetFrameProps(self, **kwargs: Any) -> VideoNode: ...
            @_Wrapper.Function
            def SetVideoCache(self, mode: int | None = None, fixedsize: int | None = None, maxsize: int | None = None, maxhistory: int | None = None) -> None: ...
            @_Wrapper.Function
            def ShufflePlanes(self, planes: int | _SequenceLike[int], colorfamily: int, prop_src: VideoNode | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Sobel(self, planes: int | _SequenceLike[int] | None = None, scale: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Splice(self, mismatch: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def SplitPlanes(self) -> VideoNode | list[VideoNode]: ...
            @_Wrapper.Function
            def StackHorizontal(self) -> VideoNode: ...
            @_Wrapper.Function
            def StackVertical(self) -> VideoNode: ...
            @_Wrapper.Function
            def Transpose(self) -> VideoNode: ...
            @_Wrapper.Function
            def Trim(self, first: int | None = None, last: int | None = None, length: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Turn180(self) -> VideoNode: ...

    class _AudioNode_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def AssumeSampleRate(self, src: AudioNode | None = None, samplerate: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioGain(self, gain: float | _SequenceLike[float] | None = None, overflow_error: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioLoop(self, times: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioMix(self, matrix: float | _SequenceLike[float], channels_out: int | _SequenceLike[int], overflow_error: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def AudioReverse(self) -> AudioNode: ...
            @_Wrapper.Function
            def AudioSplice(self) -> AudioNode: ...
            @_Wrapper.Function
            def AudioTrim(self, first: int | None = None, last: int | None = None, length: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def BlankAudio(self, channels: int | _SequenceLike[int] | None = None, bits: int | None = None, sampletype: int | None = None, samplerate: int | None = None, length: int | None = None, keep: int | None = None) -> AudioNode: ...
            @_Wrapper.Function
            def SetAudioCache(self, mode: int | None = None, fixedsize: int | None = None, maxsize: int | None = None, maxhistory: int | None = None) -> None: ...
            @_Wrapper.Function
            def ShuffleChannels(self, channels_in: int | _SequenceLike[int], channels_out: int | _SequenceLike[int]) -> AudioNode: ...
            @_Wrapper.Function
            def SplitChannels(self) -> AudioNode | list[AudioNode]: ...

# </implementation/std>

# <implementation/zsmooth>
class _zsmooth:
    class _Core_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def BackwardClense(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CCD(self, clip: VideoNode, threshold: float | None = None, temporal_radius: int | None = None, points: int | _SequenceLike[int] | None = None, scale: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Clense(self, clip: VideoNode, previous: VideoNode | None = None, next: VideoNode | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DegrainMedian(self, clip: VideoNode, limit: float | _SequenceLike[float] | None = None, mode: int | _SequenceLike[int] | None = None, interlaced: int | None = None, norow: int | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FluxSmoothST(self, clip: VideoNode, temporal_threshold: float | _SequenceLike[float] | None = None, spatial_threshold: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FluxSmoothT(self, clip: VideoNode, temporal_threshold: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def ForwardClense(self, clip: VideoNode, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def InterQuartileMean(self, clip: VideoNode, radius: int | _SequenceLike[int] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Median(self, clip: VideoNode, radius: int | _SequenceLike[int] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def RemoveGrain(self, clip: VideoNode, mode: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def Repair(self, clip: VideoNode, repairclip: VideoNode, mode: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def SmartMedian(self, clip: VideoNode, radius: int | _SequenceLike[int] | None = None, threshold: float | _SequenceLike[float] | None = None, scalep: int | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TTempSmooth(self, clip: VideoNode, maxr: int | None = None, thresh: int | _SequenceLike[int] | None = None, mdiff: int | _SequenceLike[int] | None = None, strength: int | None = None, scthresh: float | None = None, fp: int | None = None, pfclip: VideoNode | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TemporalMedian(self, clip: VideoNode, radius: int | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TemporalRepair(self, clip: VideoNode, repairclip: VideoNode, mode: int | _SequenceLike[int] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TemporalSoften(self, clip: VideoNode, radius: int | None = None, threshold: float | _SequenceLike[float] | None = None, scenechange: int | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def VerticalCleaner(self, clip: VideoNode, mode: int | _SequenceLike[int]) -> VideoNode: ...

    class _VideoNode_bound:
        class Plugin(_VSPlugin):
            @_Wrapper.Function
            def BackwardClense(self, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def CCD(self, threshold: float | None = None, temporal_radius: int | None = None, points: int | _SequenceLike[int] | None = None, scale: float | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Clense(self, previous: VideoNode | None = None, next: VideoNode | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def DegrainMedian(self, limit: float | _SequenceLike[float] | None = None, mode: int | _SequenceLike[int] | None = None, interlaced: int | None = None, norow: int | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FluxSmoothST(self, temporal_threshold: float | _SequenceLike[float] | None = None, spatial_threshold: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def FluxSmoothT(self, temporal_threshold: float | _SequenceLike[float] | None = None, planes: int | _SequenceLike[int] | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def ForwardClense(self, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def InterQuartileMean(self, radius: int | _SequenceLike[int] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def Median(self, radius: int | _SequenceLike[int] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def RemoveGrain(self, mode: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def Repair(self, repairclip: VideoNode, mode: int | _SequenceLike[int]) -> VideoNode: ...
            @_Wrapper.Function
            def SmartMedian(self, radius: int | _SequenceLike[int] | None = None, threshold: float | _SequenceLike[float] | None = None, scalep: int | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TTempSmooth(self, maxr: int | None = None, thresh: int | _SequenceLike[int] | None = None, mdiff: int | _SequenceLike[int] | None = None, strength: int | None = None, scthresh: float | None = None, fp: int | None = None, pfclip: VideoNode | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TemporalMedian(self, radius: int | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TemporalRepair(self, repairclip: VideoNode, mode: int | _SequenceLike[int] | None = None, planes: int | _SequenceLike[int] | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def TemporalSoften(self, radius: int | None = None, threshold: float | _SequenceLike[float] | None = None, scenechange: int | None = None, scalep: int | None = None) -> VideoNode: ...
            @_Wrapper.Function
            def VerticalCleaner(self, mode: int | _SequenceLike[int]) -> VideoNode: ...

# </implementation/zsmooth>

# </plugins/implementations>

class VideoOutputTuple(NamedTuple):
    clip: VideoNode
    alpha: VideoNode | None
    alt_output: Literal[0, 1, 2]

def clear_output(index: int = 0) -> None: ...
def clear_outputs() -> None: ...
def get_outputs() -> MappingProxyType[int, VideoOutputTuple | AudioNode]: ...
def get_output(index: int = 0) -> VideoOutputTuple | AudioNode: ...

def construct_signature(
    signature: str | Function, return_signature: str, injected: bool | None = None, name: str | None = None
) -> Signature: ...
def _construct_type(signature: str) -> Any: ...
def _construct_parameter(signature: str) -> Any: ...
def _construct_repr_wrap(value: str | Enum | VideoFormat | Iterator[str]) -> str: ...
def _construct_repr(obj: Any, **kwargs: Any) -> str: ...
